{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.4.21/rucountablenouns-1.4.21.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.4.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "xxdahi6bcrh6lmw6znov3dh2hm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jvm-1.4.21.jar",
          "url": "rucountablenouns-jvm-1.4.21.jar",
          "size": 57977,
          "sha512": "03d73c129630f02f3d6b337b13ad15694452e86488719429bcb80b3653b06fcd63253dcf3ae69849362ec4b6bc16df447a415171ca2352aeea2f0841049a578c",
          "sha256": "eb668e7723fb01af30d9d20f2f1d8ff14abab5104cb38969de17ff400c426f71",
          "sha1": "fb70a727bda3cb6b897663586fc671a9edd657b3",
          "md5": "ae0352beb622b9a522e04f3fa84d3286"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jvm-1.4.21.jar",
          "url": "rucountablenouns-jvm-1.4.21.jar",
          "size": 57977,
          "sha512": "03d73c129630f02f3d6b337b13ad15694452e86488719429bcb80b3653b06fcd63253dcf3ae69849362ec4b6bc16df447a415171ca2352aeea2f0841049a578c",
          "sha256": "eb668e7723fb01af30d9d20f2f1d8ff14abab5104cb38969de17ff400c426f71",
          "sha1": "fb70a727bda3cb6b897663586fc671a9edd657b3",
          "md5": "ae0352beb622b9a522e04f3fa84d3286"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.4.21/rucountablenouns-metadata-1.4.21.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.4.21"
      }
    }
  ]
}
