{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.4.21/rucountablenouns-1.4.21.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.4.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "aubrzm5j3zdgjom7wy6n3t2frm"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jvm-1.4.21.jar",
          "url": "rucountablenouns-jvm-1.4.21.jar",
          "size": 57977,
          "sha512": "49d53ecd6f7d351aff2aabda14ecb31c8fb46fe3f8b8cd6031e1bcaa9cc75c666e9d47defc1711ee5f32bab2b249e1e22fa5542b7b9d471240358f67dbdd1ee8",
          "sha256": "053c476ff3a4c9e8b268b3dbd2bd928f4598ec6f2f3921ebb5e48720440d2886",
          "sha1": "8615e5af783aa1bcbde7948fcf21a54633fe5085",
          "md5": "e5f74a5763db420dd69bbbb5bcbbafe3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jvm-1.4.21.jar",
          "url": "rucountablenouns-jvm-1.4.21.jar",
          "size": 57977,
          "sha512": "49d53ecd6f7d351aff2aabda14ecb31c8fb46fe3f8b8cd6031e1bcaa9cc75c666e9d47defc1711ee5f32bab2b249e1e22fa5542b7b9d471240358f67dbdd1ee8",
          "sha256": "053c476ff3a4c9e8b268b3dbd2bd928f4598ec6f2f3921ebb5e48720440d2886",
          "sha1": "8615e5af783aa1bcbde7948fcf21a54633fe5085",
          "md5": "e5f74a5763db420dd69bbbb5bcbbafe3"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.4.21/rucountablenouns-metadata-1.4.21.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.4.21"
      }
    }
  ]
}
