{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.4.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "dp625pdixrdwtbv3wrprqcbavq"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-metadata-1.4.21-2.jar",
          "url": "rucountablenouns-1.4.21-2.jar",
          "size": 12841,
          "sha512": "16fd0e8b3aacee6ebb7164c847dfd395ccb39213f659729d9ca5a12251306180ee3947e60b6e77533726c22780d053824fa17f7de81ffe3921b5340850f90b1e",
          "sha256": "d5fc2d561b0cc038f716acd2e0649a9b4b0ddfd2e17ced1a58b5065d83326b0f",
          "sha1": "996c7c2f611bb7f75619212344bc1f847f52de5d",
          "md5": "dc8231c97731e8f316869b079d958c2b"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.4.21-2/rucountablenouns-js-1.4.21-2.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.4.21-2"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.4.21-2/rucountablenouns-js-1.4.21-2.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.4.21-2"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.4.21-2/rucountablenouns-js-1.4.21-2.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.4.21-2"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.4.21-2/rucountablenouns-js-1.4.21-2.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.4.21-2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../rucountablenouns-jvm/1.4.21-2/rucountablenouns-jvm-1.4.21-2.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-jvm",
        "version": "1.4.21-2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../rucountablenouns-jvm/1.4.21-2/rucountablenouns-jvm-1.4.21-2.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-jvm",
        "version": "1.4.21-2"
      }
    }
  ]
}
