{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.4.30-M1/rucountablenouns-1.4.30-M1.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.4.30-M1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "tj24ihsghjarbhopxsvsmyd4fm"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30-M1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-M1"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jslegacy-1.4.30-M1.jar",
          "url": "rucountablenouns-js-1.4.30-M1.jar",
          "size": 38081,
          "sha512": "0783d0bd7dc1a792923de60cc23da41d788acef9491fd6674cba0effb2308668a7e9c42317ba2226ee302c576d0a35910596735baa35ce0140ff491d2387358d",
          "sha256": "fec60389d4cf946b23ad6d11cf428832a4bbd57f3c6b412d87f720ef599fd659",
          "sha1": "1d157cd76813d66e7e2d51701ed91ca36846e38e",
          "md5": "cc76c53878a20ff2b886f71e98bc5708"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30-M1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-M1"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jslegacy-1.4.30-M1.jar",
          "url": "rucountablenouns-js-1.4.30-M1.jar",
          "size": 38081,
          "sha512": "0783d0bd7dc1a792923de60cc23da41d788acef9491fd6674cba0effb2308668a7e9c42317ba2226ee302c576d0a35910596735baa35ce0140ff491d2387358d",
          "sha256": "fec60389d4cf946b23ad6d11cf428832a4bbd57f3c6b412d87f720ef599fd659",
          "sha1": "1d157cd76813d66e7e2d51701ed91ca36846e38e",
          "md5": "cc76c53878a20ff2b886f71e98bc5708"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30-M1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-M1"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jsir-1.4.30-M1.klib",
          "url": "rucountablenouns-js-1.4.30-M1.klib",
          "size": 51539,
          "sha512": "9f2d5a052d4c5a7a593cae672f28b3c885d16d5e69be5fe9f7de8368aafc562835e45a533f42fb850a84dbd093b3af1192d6ec08f682072b632a6a15a3f19d79",
          "sha256": "a1f625d77d6c6abc877b5e751d46a5fca8a3d22096b7fec152623a83da53ec1d",
          "sha1": "cbeb95e406dad15ae982c037028ea299a7b8aff7",
          "md5": "eb9076f41a9144e4750df0255fa93589"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.30-M1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-M1"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jsir-1.4.30-M1.klib",
          "url": "rucountablenouns-js-1.4.30-M1.klib",
          "size": 51539,
          "sha512": "9f2d5a052d4c5a7a593cae672f28b3c885d16d5e69be5fe9f7de8368aafc562835e45a533f42fb850a84dbd093b3af1192d6ec08f682072b632a6a15a3f19d79",
          "sha256": "a1f625d77d6c6abc877b5e751d46a5fca8a3d22096b7fec152623a83da53ec1d",
          "sha1": "cbeb95e406dad15ae982c037028ea299a7b8aff7",
          "md5": "eb9076f41a9144e4750df0255fa93589"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.4.30-M1/rucountablenouns-metadata-1.4.30-M1.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.4.30-M1"
      }
    }
  ]
}
