{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.4.21-2/rucountablenouns-1.4.21-2.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.4.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "mxq7mzm6i5enfmczsdvd6xyd6a"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jslegacy-1.4.21-2.jar",
          "url": "rucountablenouns-js-1.4.21-2.jar",
          "size": 38077,
          "sha512": "a6cd6260d6201f0193bbea66157c295ac257432342b784ebbdf66778c930bd7645946785ce1659f3d331e720bfdc03d2d4daa9c96c74512bdeca4a719b824b90",
          "sha256": "4edd3603b3b941176ed68078171cf05fd788a13684350119cc87f0dffd649b06",
          "sha1": "4af76453fb7685beca462ebbcf8616156a36987c",
          "md5": "1ea1af81e110a7489d8306762f6aa3ab"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jslegacy-1.4.21-2.jar",
          "url": "rucountablenouns-js-1.4.21-2.jar",
          "size": 38077,
          "sha512": "a6cd6260d6201f0193bbea66157c295ac257432342b784ebbdf66778c930bd7645946785ce1659f3d331e720bfdc03d2d4daa9c96c74512bdeca4a719b824b90",
          "sha256": "4edd3603b3b941176ed68078171cf05fd788a13684350119cc87f0dffd649b06",
          "sha1": "4af76453fb7685beca462ebbcf8616156a36987c",
          "md5": "1ea1af81e110a7489d8306762f6aa3ab"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jsir-1.4.21-2.klib",
          "url": "rucountablenouns-js-1.4.21-2.klib",
          "size": 54647,
          "sha512": "647515bf8377211b581df42d515ea6d02247687755b5bb36c7304f9ac40ed738b3f0ddf3672a87ee03085855ee61c621627b908e45a5aa2107a13ebfaec2e808",
          "sha256": "4d4ee6a4537f9f5e660b8f7e6f3feaf38c343e9648f79d14ebdfc7b0902768d6",
          "sha1": "dae580b27f4163228bc3cdaf67ab19812adf107d",
          "md5": "ebb4078d700bb131722de980220bbcc6"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jsir-1.4.21-2.klib",
          "url": "rucountablenouns-js-1.4.21-2.klib",
          "size": 54647,
          "sha512": "647515bf8377211b581df42d515ea6d02247687755b5bb36c7304f9ac40ed738b3f0ddf3672a87ee03085855ee61c621627b908e45a5aa2107a13ebfaec2e808",
          "sha256": "4d4ee6a4537f9f5e660b8f7e6f3feaf38c343e9648f79d14ebdfc7b0902768d6",
          "sha1": "dae580b27f4163228bc3cdaf67ab19812adf107d",
          "md5": "ebb4078d700bb131722de980220bbcc6"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.4.21-2/rucountablenouns-metadata-1.4.21-2.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.4.21-2"
      }
    }
  ]
}
