{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.0/rucountablenouns-1.0.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "gd2tzlug2nfftmu4qouazmfcqi"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rucountablenouns-jvm-1.0.jar",
          "url": "rucountablenouns-jvm-1.0.jar",
          "size": 58076,
          "sha512": "164f694ba7249247b23645a35306faee0bfc97a65c704826710d8f407c745c012286567d5cb4a0fe2a950c866129797fc1f04a8b8fa51770276300e35522d117",
          "sha256": "bf39dec257a057d7503b36040030e5a5bbf14bd7c14cbefa49bff7acd9167888",
          "sha1": "eaacfcabec3a5e9de7df69e5b8376b5aa906dd52",
          "md5": "c6f11d63b6db80d35445e691e3d969f4"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jvm-1.0.jar",
          "url": "rucountablenouns-jvm-1.0.jar",
          "size": 58076,
          "sha512": "164f694ba7249247b23645a35306faee0bfc97a65c704826710d8f407c745c012286567d5cb4a0fe2a950c866129797fc1f04a8b8fa51770276300e35522d117",
          "sha256": "bf39dec257a057d7503b36040030e5a5bbf14bd7c14cbefa49bff7acd9167888",
          "sha1": "eaacfcabec3a5e9de7df69e5b8376b5aa906dd52",
          "md5": "c6f11d63b6db80d35445e691e3d969f4"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.0/rucountablenouns-metadata-1.0.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.0"
      }
    }
  ]
}
