{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.0/rucountablenouns-1.0.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "ljd6qpzzprekje7qdponj7jrdu"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "files": [
        {
          "name": "rucountablenouns-jvm-1.0.jar",
          "url": "rucountablenouns-jvm-1.0.jar",
          "size": 58020,
          "sha512": "334cb5177ed570eac8cf422cb5a0c99c1bb203acf8c149c27dd11fae609dc546f205917f44083124e7329b325fcaefa0f3892ed2921596f0c533244a5e627514",
          "sha256": "5bbf4e232dc7cca3e7ba6aedae90e7656d7c89bfe93812565825d770295c3840",
          "sha1": "5c5303d274aab2916a43d560726b2b2fa9560006",
          "md5": "49e1421fbdb38551317804e54f5ffcca"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-rc"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jvm-1.0.jar",
          "url": "rucountablenouns-jvm-1.0.jar",
          "size": 58020,
          "sha512": "334cb5177ed570eac8cf422cb5a0c99c1bb203acf8c149c27dd11fae609dc546f205917f44083124e7329b325fcaefa0f3892ed2921596f0c533244a5e627514",
          "sha256": "5bbf4e232dc7cca3e7ba6aedae90e7656d7c89bfe93812565825d770295c3840",
          "sha1": "5c5303d274aab2916a43d560726b2b2fa9560006",
          "md5": "49e1421fbdb38551317804e54f5ffcca"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.0/rucountablenouns-metadata-1.0.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.0"
      }
    }
  ]
}
