{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.0/rucountablenouns-1.0.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "tgfncns32bhi3bmltu7rj7e24m"
    }
  },
  "variants": [
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-rc"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jvm-1.0.jar",
          "url": "rucountablenouns-jvm-1.0.jar",
          "size": 58020,
          "sha512": "698961d4a57d5fca4f2cf4d2ba4534ddeabb556dc3e9f750aaa7d8a2c0275e227dbe8a8e00ea54ead50fd558c257e0fc61078b1ed7b164e8f40b82a0e1782e57",
          "sha256": "1ae76cd2cca13c4310d9403b21a937db956a7384943233f1ceeb5e0b4145ebbd",
          "sha1": "7e1f404b4266b61f6fa63f321ddd244637fd1461",
          "md5": "c6be8d100fbef076fe65bddfe110fd0e"
        }
      ]
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-rc"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jvm-1.0.jar",
          "url": "rucountablenouns-jvm-1.0.jar",
          "size": 58020,
          "sha512": "698961d4a57d5fca4f2cf4d2ba4534ddeabb556dc3e9f750aaa7d8a2c0275e227dbe8a8e00ea54ead50fd558c257e0fc61078b1ed7b164e8f40b82a0e1782e57",
          "sha256": "1ae76cd2cca13c4310d9403b21a937db956a7384943233f1ceeb5e0b4145ebbd",
          "sha1": "7e1f404b4266b61f6fa63f321ddd244637fd1461",
          "md5": "c6be8d100fbef076fe65bddfe110fd0e"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.0/rucountablenouns-metadata-1.0.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.0"
      }
    }
  ]
}
