{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.0/rucountablenouns-1.0.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "ndccp2kxbfawpeuzsip4kw4k2e"
    }
  },
  "variants": [
    {
      "name": "jsLegacy-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-rc"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jslegacy-1.0.jar",
          "url": "rucountablenouns-js-1.0.jar",
          "size": 37995,
          "sha512": "84b951f325e16d70c433f92ae358860533a7fd3a2e64f1933db8d12a9b93f3d6d434f698a0a009483e87e51b28b31f355a3c35215c6891b5facd6331a3a5b932",
          "sha256": "205295df97b00bfcdc6bc9a4badee6f5820a5de15961f8d38f555078dc99d307",
          "sha1": "d354217c252e58646b46d0fea81646653280c742",
          "md5": "3c915191317b03effee6e41074455a87"
        }
      ]
    },
    {
      "name": "jsLegacy-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-rc"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jslegacy-1.0.jar",
          "url": "rucountablenouns-js-1.0.jar",
          "size": 37995,
          "sha512": "84b951f325e16d70c433f92ae358860533a7fd3a2e64f1933db8d12a9b93f3d6d434f698a0a009483e87e51b28b31f355a3c35215c6891b5facd6331a3a5b932",
          "sha256": "205295df97b00bfcdc6bc9a4badee6f5820a5de15961f8d38f555078dc99d307",
          "sha1": "d354217c252e58646b46d0fea81646653280c742",
          "md5": "3c915191317b03effee6e41074455a87"
        }
      ]
    },
    {
      "name": "jsIr-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-rc"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jsir-1.0.klib",
          "url": "rucountablenouns-js-1.0.klib",
          "size": 54366,
          "sha512": "ab34c9597c06c02ad61a47803ebd0c2c6e88f13eadf455d636a9eb320187ecff52668decf930d8952d30115e0b07e179a24cdf6bcb8429c3dce9706016af074a",
          "sha256": "80fc5b753c6d9dc5898c0e97b3ff907ed91d7bf51023f5603f6615f29d79f2ff",
          "sha1": "8f4de6e93f889a722c4bedd4cd2dc6f58b2612d3",
          "md5": "dbcd81019ed9eafa47afebdc8f1d27b7"
        }
      ]
    },
    {
      "name": "jsIr-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0-rc"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-rc"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jsir-1.0.klib",
          "url": "rucountablenouns-js-1.0.klib",
          "size": 54366,
          "sha512": "ab34c9597c06c02ad61a47803ebd0c2c6e88f13eadf455d636a9eb320187ecff52668decf930d8952d30115e0b07e179a24cdf6bcb8429c3dce9706016af074a",
          "sha256": "80fc5b753c6d9dc5898c0e97b3ff907ed91d7bf51023f5603f6615f29d79f2ff",
          "sha1": "8f4de6e93f889a722c4bedd4cd2dc6f58b2612d3",
          "md5": "dbcd81019ed9eafa47afebdc8f1d27b7"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.0/rucountablenouns-metadata-1.0.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.0"
      }
    }
  ]
}
