{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.0/rucountablenouns-1.0.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "sabi2gt7fjb4npxvbhbxmdltee"
    }
  },
  "variants": [
    {
      "name": "jsLegacy-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jslegacy-1.0.jar",
          "url": "rucountablenouns-js-1.0.jar",
          "size": 38035,
          "sha512": "05f29cd0b8572944e0c592fe245c2f0b91e12dbc2302ee4cacab61466f383c969f643d497f2cddd3bfa56bfa88a96f1e1852eba32bc276ac1caa6e9d955818a2",
          "sha256": "7340745faebb7c46e6ed6b35042a8532008163a8da9bb346d6d2d786da0d1a99",
          "sha1": "48bda776892d8b06805d976e9eba040446532f67",
          "md5": "3d5a4905425e25067b93c766f14e4e2e"
        }
      ]
    },
    {
      "name": "jsLegacy-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jslegacy-1.0.jar",
          "url": "rucountablenouns-js-1.0.jar",
          "size": 38035,
          "sha512": "05f29cd0b8572944e0c592fe245c2f0b91e12dbc2302ee4cacab61466f383c969f643d497f2cddd3bfa56bfa88a96f1e1852eba32bc276ac1caa6e9d955818a2",
          "sha256": "7340745faebb7c46e6ed6b35042a8532008163a8da9bb346d6d2d786da0d1a99",
          "sha1": "48bda776892d8b06805d976e9eba040446532f67",
          "md5": "3d5a4905425e25067b93c766f14e4e2e"
        }
      ]
    },
    {
      "name": "jsIr-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jsir-1.0.klib",
          "url": "rucountablenouns-js-1.0.klib",
          "size": 54363,
          "sha512": "c5bfed815ac4b4060346baad4ef9bb350caeeac9a2396a0c5f37c96587671dc93874ec3b7fd5f8ed9483a61daa67334efd15b79b4faeb81dd7859ca680f6f93f",
          "sha256": "a43829f907ff5b817ab82e6aaaf66ece35eb62ffacfee4615bb0400498234015",
          "sha1": "df110b4dd8fcdbe2f85f2b29e7566ab09f525ccc",
          "md5": "4235ff4ada4bad8e329a0fa3da9f25c3"
        }
      ]
    },
    {
      "name": "jsIr-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jsir-1.0.klib",
          "url": "rucountablenouns-js-1.0.klib",
          "size": 54363,
          "sha512": "c5bfed815ac4b4060346baad4ef9bb350caeeac9a2396a0c5f37c96587671dc93874ec3b7fd5f8ed9483a61daa67334efd15b79b4faeb81dd7859ca680f6f93f",
          "sha256": "a43829f907ff5b817ab82e6aaaf66ece35eb62ffacfee4615bb0400498234015",
          "sha1": "df110b4dd8fcdbe2f85f2b29e7566ab09f525ccc",
          "md5": "4235ff4ada4bad8e329a0fa3da9f25c3"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.0/rucountablenouns-metadata-1.0.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.0"
      }
    }
  ]
}
