{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.0/rucountablenouns-1.0.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.3",
      "buildId": "gd2tzlug2nfftmu4qouazmfcqi"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "files": [
        {
          "name": "rucountablenouns-js-1.0.jar",
          "url": "rucountablenouns-js-1.0.jar",
          "size": 35960,
          "sha512": "9aa1a193d1a3867f75a3159b721852f906679ad1231552ad618247d9542525a5f0c0e85ac987fc3be72e12d900325c916395f48a26d9cb4496763af8b7ca5494",
          "sha256": "8e565930b5682ec178f2fd983606ca5eab0c12c98314286b577df000f0e9b7ef",
          "sha1": "9fc09fab1dcaee3c4d9d9477d6509cc8d27bcdda",
          "md5": "0b3d4e7af0600e495523aee3084490cd"
        }
      ]
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.3.70"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.3.70"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-js-1.0.jar",
          "url": "rucountablenouns-js-1.0.jar",
          "size": 35960,
          "sha512": "9aa1a193d1a3867f75a3159b721852f906679ad1231552ad618247d9542525a5f0c0e85ac987fc3be72e12d900325c916395f48a26d9cb4496763af8b7ca5494",
          "sha256": "8e565930b5682ec178f2fd983606ca5eab0c12c98314286b577df000f0e9b7ef",
          "sha1": "9fc09fab1dcaee3c4d9d9477d6509cc8d27bcdda",
          "md5": "0b3d4e7af0600e495523aee3084490cd"
        }
      ]
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.0/rucountablenouns-metadata-1.0.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.0"
      }
    }
  ]
}
