{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.0/rucountablenouns-1.0.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "7q52m74wjnaqzciohmgqfuqsl4"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.0-rc"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-metadata-1.0.jar",
          "url": "rucountablenouns-metadata-1.0.jar",
          "size": 12840,
          "sha512": "d504c93058e8187f1463c0a799c8b070211817751c1863765f67961e758183eaf0fad5e2d1844489e33e34721f99e813d45f2c2b6d6f5362821ac0c1835e12da",
          "sha256": "b0a6cfd9862fd88b37977ec0102e496dd8ac3d8dda9a96c0ab699717822c574d",
          "sha1": "c92620b7a8a93276318ac7d33a8a04e1849bd910",
          "md5": "4ac874f8cd61a68f5321f4d25aaef474"
        }
      ]
    }
  ]
}
