{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.0/rucountablenouns-1.0.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "vhy7n4c2y5gfnkrxygk7nygiwi"
    }
  },
  "variants": [
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "files": [
        {
          "name": "rucountablenouns-metadata-1.0.jar",
          "url": "rucountablenouns-metadata-1.0.jar",
          "size": 12840,
          "sha512": "0deedfeed7e9ea9a3bf9c20cf2e224032533e0cbe23a1b2a490ee4b03cb0a497b8de15b16cc98efcd25537730adf83185a9a7995928a3cf5d16cec34b5ad9e47",
          "sha256": "f52290376136a503ac45e236aa3baa26a87d405e850dbeb02bdc1b46941e43a1",
          "sha1": "e915989feea59a66dc9373400922e1b215e9e3b6",
          "md5": "9326546022ac89c01f23b2ab2798c8be"
        }
      ]
    }
  ]
}
