{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.4.30-M1/rucountablenouns-1.4.30-M1.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.4.30-M1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "kbs37mbbcbdzldv5m7hikrzsoa"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-M1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-M1"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jvm-1.4.30-M1.jar",
          "url": "rucountablenouns-jvm-1.4.30-M1.jar",
          "size": 58104,
          "sha512": "2243c905cb475e854171600a26cb4faf41ef30588e4edf457f558d134b04b0d488c71f3ca480909c01965117b68544d67c947ceac0a7954be5a964e4850a4e40",
          "sha256": "6beab5ca9004dc81d17c522f3fc14d0ec1e7e4581a3cf47e79d6f8a51f5b674e",
          "sha1": "21cb24413d1d71f881376c17261c41c9721cc8c7",
          "md5": "cfff706294e8482828da8dd322a67562"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.30-M1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-M1"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jvm-1.4.30-M1.jar",
          "url": "rucountablenouns-jvm-1.4.30-M1.jar",
          "size": 58104,
          "sha512": "2243c905cb475e854171600a26cb4faf41ef30588e4edf457f558d134b04b0d488c71f3ca480909c01965117b68544d67c947ceac0a7954be5a964e4850a4e40",
          "sha256": "6beab5ca9004dc81d17c522f3fc14d0ec1e7e4581a3cf47e79d6f8a51f5b674e",
          "sha1": "21cb24413d1d71f881376c17261c41c9721cc8c7",
          "md5": "cfff706294e8482828da8dd322a67562"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.4.30-M1/rucountablenouns-metadata-1.4.30-M1.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.4.30-M1"
      }
    }
  ]
}
