{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns-jvm/1.4.30-M1/rucountablenouns-jvm-1.4.30-M1.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns-jvm",
    "version": "1.4.30-M1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "peaizslun5ggpg6zp34tsnw4pm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-M1"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-metadata-1.4.30-M1.jar",
          "url": "rucountablenouns-metadata-1.4.30-M1.jar",
          "size": 12843,
          "sha512": "69c0b0dc63dadb8f2545c8c08aa76c6244de1d34eaca23865d00a3531d9f0a5e1da47c0b52f0202abfbc411f5f963c2f37451309ea8da574c93d470d4901be67",
          "sha256": "e267d17e1afbcec170f87dcbcf89fe3fa3e02d5d53d6a57fbc43b90051842c73",
          "sha1": "a721f80d7dec4b4aa102b796d4ff40d81c83e2e0",
          "md5": "2da9ced585331a68e602eafadc942d33"
        }
      ]
    }
  ]
}
