{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.4.30-M1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "veg6ds4dljc45izjvlepoelp6q"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.30-M1"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-metadata-1.4.30-M1.jar",
          "url": "rucountablenouns-1.4.30-M1.jar",
          "size": 12843,
          "sha512": "bb2761c1c2c13e6598422896324ba7bc733f37aa26357966a175c1e95aaa4efae7c90d4cb93c77927068516058af0b0b0e1c1de637ba53408a0e3c67a84ff90c",
          "sha256": "8d786c471d683471db87d0acb93c1d1c9be786df0cc54511afea0b00a3348fc1",
          "sha1": "4823be993b649b8989ea86be62f69cf52f2f3303",
          "md5": "8ca6e28d13a4434136a234d20a42f948"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.4.30-M1/rucountablenouns-js-1.4.30-M1.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.4.30-M1"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.4.30-M1/rucountablenouns-js-1.4.30-M1.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.4.30-M1"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.4.30-M1/rucountablenouns-js-1.4.30-M1.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.4.30-M1"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.4.30-M1/rucountablenouns-js-1.4.30-M1.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.4.30-M1"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../rucountablenouns-jvm/1.4.30-M1/rucountablenouns-jvm-1.4.30-M1.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-jvm",
        "version": "1.4.30-M1"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../rucountablenouns-jvm/1.4.30-M1/rucountablenouns-jvm-1.4.30-M1.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-jvm",
        "version": "1.4.30-M1"
      }
    }
  ]
}
