{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns-jvm/1.4.21/rucountablenouns-jvm-1.4.21.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns-jvm",
    "version": "1.4.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "wlar5w4pwvhkvggszn7dl56ydm"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-metadata-1.4.21.jar",
          "url": "rucountablenouns-metadata-1.4.21.jar",
          "size": 12841,
          "sha512": "25c21fbac78f86b388ae7941bd3bc50526868ff5bf5d7ea19f06643239bb49217fe84fe99d99e7abbeed31ef883be374c79de76fb7250b45d77719f1586e15b8",
          "sha256": "c755d6f07f13fc00c628b522312b76a2ac53df95f32163a7f4807da58c1bd883",
          "sha1": "89f73edee763b7db4a300dafa53dc16c10b59240",
          "md5": "b9dbc454787f47efd93bd8ed0dcbc2f1"
        }
      ]
    }
  ]
}
