{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "7mkn34ykjrg6vnw2d4lamfzxkq"
    }
  },
  "variants": [
    {
      "name": "js-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.0/rucountablenouns-js-1.0.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.0"
      }
    },
    {
      "name": "js-runtime",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.0/rucountablenouns-js-1.0.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.0"
      }
    },
    {
      "name": "jvm-api",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../rucountablenouns-jvm/1.0/rucountablenouns-jvm-1.0.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "jvm-runtime",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../rucountablenouns-jvm/1.0/rucountablenouns-jvm-1.0.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-jvm",
        "version": "1.0"
      }
    },
    {
      "name": "metadata-api",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.0/rucountablenouns-metadata-1.0.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.0"
      }
    }
  ]
}
