{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.4.21/rucountablenouns-1.4.21.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.4.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "bbn6nm7rf5gjhongbzd6sy2y7q"
    }
  },
  "variants": [
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jslegacy-1.4.21.jar",
          "url": "rucountablenouns-js-1.4.21.jar",
          "size": 38077,
          "sha512": "734af801d62578c2257fdb70e8bcae7cf51368e3c429e88ad4dd7f86115ad654d52d85ed53417600bd31ba7e28154f33f9af96186315d4a7185f8922cb457d19",
          "sha256": "5b23b31cfb0ee04ac5686f65f7ac87ad9cd6b57cd093c2894d26ed8270fb6efe",
          "sha1": "211192dd34d3035cc2175d318e0b57149fa85bfa",
          "md5": "3a45fde93cd478bb2b572abeefab5ecb"
        }
      ]
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jslegacy-1.4.21.jar",
          "url": "rucountablenouns-js-1.4.21.jar",
          "size": 38077,
          "sha512": "734af801d62578c2257fdb70e8bcae7cf51368e3c429e88ad4dd7f86115ad654d52d85ed53417600bd31ba7e28154f33f9af96186315d4a7185f8922cb457d19",
          "sha256": "5b23b31cfb0ee04ac5686f65f7ac87ad9cd6b57cd093c2894d26ed8270fb6efe",
          "sha1": "211192dd34d3035cc2175d318e0b57149fa85bfa",
          "md5": "3a45fde93cd478bb2b572abeefab5ecb"
        }
      ]
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jsir-1.4.21.klib",
          "url": "rucountablenouns-js-1.4.21.klib",
          "size": 54645,
          "sha512": "49201f2bb3970822868aa00ef4e71e634faf354f80d35531705cdb039f44fa098fae27591f715f56aa59eedcd0f45937d86e113cfb1ac55e7a22919ec97c8d79",
          "sha256": "ab6e28025944cff8c37df4968999ed2f3b71eed97bfbb5637c2838d19ff36522",
          "sha1": "946dee62d8d5b6fe0f4d16582696cce128cb6ed1",
          "md5": "f48e874733fe353b3148029f16979fc7"
        }
      ]
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-js",
          "version": {
            "requires": "1.4.21"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jsir-1.4.21.klib",
          "url": "rucountablenouns-js-1.4.21.klib",
          "size": 54645,
          "sha512": "49201f2bb3970822868aa00ef4e71e634faf354f80d35531705cdb039f44fa098fae27591f715f56aa59eedcd0f45937d86e113cfb1ac55e7a22919ec97c8d79",
          "sha256": "ab6e28025944cff8c37df4968999ed2f3b71eed97bfbb5637c2838d19ff36522",
          "sha1": "946dee62d8d5b6fe0f4d16582696cce128cb6ed1",
          "md5": "f48e874733fe353b3148029f16979fc7"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.4.21/rucountablenouns-metadata-1.4.21.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.4.21"
      }
    }
  ]
}
