{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns-jvm/1.4.21-2/rucountablenouns-jvm-1.4.21-2.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns-jvm",
    "version": "1.4.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "vni3kaidgvgavf77psorxfdgp4"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-metadata-1.4.21-2.jar",
          "url": "rucountablenouns-metadata-1.4.21-2.jar",
          "size": 12841,
          "sha512": "b22bdc20283b857c106532401e4a78aba1a7df2c9fd95b98c44088c198ac44b6bd5b67dfbe75cc37bc80c612a87b2b2e7bdefbd81931d43eac0f304f49033388",
          "sha256": "6ff76a8d4738b704198d6e5490f0bee00d5e5a10793393afea4940220666d99c",
          "sha1": "d2a174244b29b2ea8ca6886448bec6033b82a574",
          "md5": "053d7670aed46725af3667524fed8c85"
        }
      ]
    }
  ]
}
