{
  "formatVersion": "1.1",
  "component": {
    "url": "../../rucountablenouns/1.4.21-2/rucountablenouns-1.4.21-2.module",
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.4.21-2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "u447mjvpafgjponkkaua7zrs3q"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jvm-1.4.21-2.jar",
          "url": "rucountablenouns-jvm-1.4.21-2.jar",
          "size": 57977,
          "sha512": "ea6a2fc8e0820ca5a06bf711614199d52b858aa549aa9230647f6632b7d30e120ae85339e1f2b956aa2ae9d45a337a8869d134406e5401cd425bfa8c0d9a97a9",
          "sha256": "3b554437d918349fe9d707a24f1c6efb3a7bbedf31001d45f8698058fcfa3c4d",
          "sha1": "9ceb476091e4bfa82982784a60af19fb5f488e06",
          "md5": "b3e490e8c0e48080f4b207f1c06f1f00"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.4.21-2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21-2"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-jvm-1.4.21-2.jar",
          "url": "rucountablenouns-jvm-1.4.21-2.jar",
          "size": 57977,
          "sha512": "ea6a2fc8e0820ca5a06bf711614199d52b858aa549aa9230647f6632b7d30e120ae85339e1f2b956aa2ae9d45a337a8869d134406e5401cd425bfa8c0d9a97a9",
          "sha256": "3b554437d918349fe9d707a24f1c6efb3a7bbedf31001d45f8698058fcfa3c4d",
          "sha1": "9ceb476091e4bfa82982784a60af19fb5f488e06",
          "md5": "b3e490e8c0e48080f4b207f1c06f1f00"
        }
      ]
    },
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "available-at": {
        "url": "../../rucountablenouns-metadata/1.4.21-2/rucountablenouns-metadata-1.4.21-2.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-metadata",
        "version": "1.4.21-2"
      }
    }
  ]
}
