{
  "formatVersion": "1.1",
  "component": {
    "group": "com.aarsenij",
    "module": "rucountablenouns",
    "version": "1.4.21",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1",
      "buildId": "5itcgjqy3vew7di346xs5rh4va"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-common",
          "version": {
            "requires": "1.4.21"
          }
        }
      ],
      "files": [
        {
          "name": "rucountablenouns-metadata-1.4.21.jar",
          "url": "rucountablenouns-1.4.21.jar",
          "size": 12841,
          "sha512": "8e18e80d077a4e36149e3cd6e5a28e164ca44e2678a26797f550936c22173b7a39711dfd0116459c1ead49a10b5c938ce4573f1a9488a588e915444b670a221c",
          "sha256": "e5e334895dfbcc350608ab1c33a740e27b13d44c86237a2df9b83e255d370276",
          "sha1": "b11a5a5fb831008c0010e738e3e7dc4d40aa0fcc",
          "md5": "621bef8ae242aafed80127f7084eab1d"
        }
      ]
    },
    {
      "name": "jsLegacyApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.4.21/rucountablenouns-js-1.4.21.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.4.21"
      }
    },
    {
      "name": "jsLegacyRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "legacy",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.4.21/rucountablenouns-js-1.4.21.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.4.21"
      }
    },
    {
      "name": "jsIrApiElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.4.21/rucountablenouns-js-1.4.21.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.4.21"
      }
    },
    {
      "name": "jsIrRuntimeElements-published",
      "attributes": {
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.js.compiler": "ir",
        "org.jetbrains.kotlin.platform.type": "js"
      },
      "available-at": {
        "url": "../../rucountablenouns-js/1.4.21/rucountablenouns-js-1.4.21.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-js",
        "version": "1.4.21"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../rucountablenouns-jvm/1.4.21/rucountablenouns-jvm-1.4.21.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-jvm",
        "version": "1.4.21"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../rucountablenouns-jvm/1.4.21/rucountablenouns-jvm-1.4.21.module",
        "group": "com.aarsenij",
        "module": "rucountablenouns-jvm",
        "version": "1.4.21"
      }
    }
  ]
}
